# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yarn_spinner.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'yarn_spinner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12yarn_spinner.proto\x12\x04Yarn\"\xf9\x01\n\x07Program\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x05nodes\x18\x02 \x03(\x0b\x32\x18.Yarn.Program.NodesEntry\x12\x38\n\x0einitial_values\x18\x03 \x03(\x0b\x32 .Yarn.Program.InitialValuesEntry\x1a\x38\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.Yarn.Node:\x02\x38\x01\x1a\x43\n\x12InitialValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.Yarn.Operand:\x02\x38\x01\"\xbe\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x0cinstructions\x18\x02 \x03(\x0b\x32\x11.Yarn.Instruction\x12&\n\x06labels\x18\x03 \x03(\x0b\x32\x16.Yarn.Node.LabelsEntry\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x1a\n\x12sourceTextStringID\x18\x05 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xe4\x02\n\x0bInstruction\x12(\n\x06opcode\x18\x01 \x01(\x0e\x32\x18.Yarn.Instruction.OpCode\x12\x1f\n\x08operands\x18\x02 \x03(\x0b\x32\r.Yarn.Operand\"\x89\x02\n\x06OpCode\x12\x0b\n\x07JUMP_TO\x10\x00\x12\x08\n\x04JUMP\x10\x01\x12\x0c\n\x08RUN_LINE\x10\x02\x12\x0f\n\x0bRUN_COMMAND\x10\x03\x12\x0e\n\nADD_OPTION\x10\x04\x12\x10\n\x0cSHOW_OPTIONS\x10\x05\x12\x0f\n\x0bPUSH_STRING\x10\x06\x12\x0e\n\nPUSH_FLOAT\x10\x07\x12\r\n\tPUSH_BOOL\x10\x08\x12\r\n\tPUSH_NULL\x10\t\x12\x11\n\rJUMP_IF_FALSE\x10\n\x12\x07\n\x03POP\x10\x0b\x12\r\n\tCALL_FUNC\x10\x0c\x12\x11\n\rPUSH_VARIABLE\x10\r\x12\x12\n\x0eSTORE_VARIABLE\x10\x0e\x12\x08\n\x04STOP\x10\x0f\x12\x0c\n\x08RUN_NODE\x10\x10\"W\n\x07Operand\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yarn_spinner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROGRAM_NODESENTRY']._loaded_options = None
  _globals['_PROGRAM_NODESENTRY']._serialized_options = b'8\001'
  _globals['_PROGRAM_INITIALVALUESENTRY']._loaded_options = None
  _globals['_PROGRAM_INITIALVALUESENTRY']._serialized_options = b'8\001'
  _globals['_NODE_LABELSENTRY']._loaded_options = None
  _globals['_NODE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_PROGRAM']._serialized_start=29
  _globals['_PROGRAM']._serialized_end=278
  _globals['_PROGRAM_NODESENTRY']._serialized_start=153
  _globals['_PROGRAM_NODESENTRY']._serialized_end=209
  _globals['_PROGRAM_INITIALVALUESENTRY']._serialized_start=211
  _globals['_PROGRAM_INITIALVALUESENTRY']._serialized_end=278
  _globals['_NODE']._serialized_start=281
  _globals['_NODE']._serialized_end=471
  _globals['_NODE_LABELSENTRY']._serialized_start=426
  _globals['_NODE_LABELSENTRY']._serialized_end=471
  _globals['_INSTRUCTION']._serialized_start=474
  _globals['_INSTRUCTION']._serialized_end=830
  _globals['_INSTRUCTION_OPCODE']._serialized_start=565
  _globals['_INSTRUCTION_OPCODE']._serialized_end=830
  _globals['_OPERAND']._serialized_start=832
  _globals['_OPERAND']._serialized_end=919
# @@protoc_insertion_point(module_scope)
